name: Create new version branch

on:
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}
          fetch-depth: '0'
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
      - name: install
        run: |
          npm install
          npm install -g lerna
      - name: Get old version
        id: get_old_version
        run: |
          echo "::set-output name=old_version::$(cat aws-s3-scanner/package.json | jq .version)"
          echo "::set-output name=old_minor_version::$(cut -d '.' -f 2 <<< $(cat aws-s3-scanner/package.json | jq -r .version))"
      - name: Create new branch
        id: create_new_branch
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git checkout -b pov/batch-${{ steps.get_old_version.outputs.old_minor_version }}
          git push --set-upstream origin pov/batch-${{ steps.get_old_version.outputs.old_minor_version }}
      - name: Bump version and push tag on pov branch
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          lerna version minor --message "New version branch pov/batch-${{ steps.get_old_version.outputs.old_minor_version }} was created [skip ci]" --yes
      - name: Bump version on develop
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git checkout ${{ github.ref_name }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          lerna version preminor --no-git-tag-version --yes
          git add -A
          git comit -m "New version was tagged %s [skip ci]"
          git push