name: Label PRs

on:
  pull_request_review:
    branches:
      - develop
      - main
    types:
      - submitted

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "gal"