name: Run E2E

on:
  pull_request_review:
    branches:
      - develop
      - main
    types:
      - submitted
  push:
    branches:
      - gh-readonly-queue/develop/**
      - gh-readonly-queue/main/**

# Reruns a check (E2E tests) if all the commits since the last check run
# were commit merges from develop
jobs:
  run_e2e:
    continue-on-error: true
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/testing-e2e.yml
    secrets: inherit
  check_failures:
    runs-on: ubuntu-latest
    needs:
      - run_e2e
    if: steps.run_e2e.outcome != 'success'
    steps:
      - name: execute
        env:
          GITHUB_TOKEN: "${{ secrets.PR_UPDATER_TOKEN }}"
        run: |    
          arr=( $(gh api -H "Accept: application/vnd.github.v3+json" /repos/cyeragit/cyera/pulls/2009/reviews | jq -c '.[] | select(.state == "APPROVED")' | jq .id) )
          for id in ${arr[@]}
          do
            gh api --method PUT \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/cyeragit/cyera/pulls/${{ github.event.number }}/reviews/$id/dismissals
            -f message='Removed review due to failed E2E tests'
          done

