on:
  pull_request:
    types:
      - auto_merge_enabled
  push:
    branches:
      - develop


name: PR auto update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PR Updater
      uses: cyeragit/pr-updater-action
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        base_branch: develop
